# Generated by Django 4.1.7 on 2023-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
