# Generated by Django 4.1.7 on 2023-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0002_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('sectionNum', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('courseID', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('departmentID', models.CharField(max_length=50)),
                ('programID', models.CharField(max_length=50)),
            ],
        ),
    ]
