# Generated by Django 4.1.7 on 2023-04-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0003_section_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='co_T',
            fields=[
                ('co_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('co1', models.FloatField()),
                ('co2', models.FloatField()),
                ('co3', models.FloatField()),
                ('co4', models.FloatField()),
                ('totalCo', models.FloatField()),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.section')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.student')),
            ],
        ),
    ]
