# Generated by Django 4.1.7 on 2023-04-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0004_co_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_t',
            name='co_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
